import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.dsl.KotlinJvmProjectExtension
import org.jetbrains.kotlin.gradle.plugin.KotlinBasePluginWrapper
import org.jetbrains.kotlin.gradle.tasks.KotlinJvmCompile

plugins {
    alias(libs.plugins.kotlin.jvm) apply false
}

allprojects {
    group = "com.doublemoon1119.mahjongcraft"
    version = "0.4.13-SNAPSHOT"

    // 必須先套用 base 插件，才能存取 base.archivesName
    apply(plugin = "base")

    // 取得 libs.versions.toml 中的預設 JVM Toolchain 版本
    val defaultToolchainVersion = rootProject.libs.versions.jvm.toolchain.get().toInt()

    // 統一設定 Kotlin Toolchain (這會自動影響 JavaCompile 和 KotlinCompile)
    plugins.withType<KotlinBasePluginWrapper> {
        extensions.configure<KotlinJvmProjectExtension> {
            jvmToolchain(defaultToolchainVersion)
        }
    }

    // 處理編譯選項與各模組自定義的 javaRelease
    afterEvaluate {
        // 檢查子模組是否有定義自定義屬性 "javaRelease"
        // 例如在子模組 build.gradle.kts 寫: extra["javaRelease"] = 17
        val customRelease = project.extensions.extraProperties.let {
            if (it.has("javaRelease")) it.get("javaRelease")?.toString()?.toInt() else null
        }

        tasks.withType<JavaCompile>().configureEach {
            options.encoding = "UTF-8"
            // 如果子模組有自定義，則覆蓋工具鏈的預設編譯版本
            if (customRelease != null) {
                options.release.set(customRelease)
            }
        }

        tasks.withType<KotlinJvmCompile>().configureEach {
            compilerOptions {
                // 如果子模組有自定義，調整 jvmTarget
                if (customRelease != null) {
                    jvmTarget.set(JvmTarget.fromTarget(customRelease.toString()))
                }
                freeCompilerArgs.add("-Xjvm-default=all")
            }
        }
    }

    val baseExtension = extensions.getByType<BasePluginExtension>()
    tasks.withType<Jar>().configureEach {
        from(rootProject.file("LICENSE")) {
            rename { "${it}_${baseExtension.archivesName.get()}" }
        }
    }

    // 統一處理資源替換
    tasks.withType<ProcessResources>().configureEach {
        val props = mapOf("version" to project.version)
        inputs.properties(props)
        filesMatching(listOf("fabric.mod.json", "META-INF/neoforge.mods.toml")) {
            expand(props)
        }
    }
}

/**
 * 開發環境切換任務
 * 用法:
 *   - 切換到 Minecraft: ./gradlew switchTarget -PtoPlatform=minecraft -PtoMcVer=v1.20.1 -PtoMcLoader=fabric
 */
tasks.register("switchTarget") {
    group = "mahjong"
    description = "Updates local.dev.properties to switch the active development platform and version."

    doLast {
        val toPlatform = project.findProperty("toPlatform")?.toString()

        if (toPlatform == null) {
            logger.error("ERROR: Missing parameter 'toPlatform'. Usage: ./gradlew switchTarget -PtoPlatform=minecraft")
            return@doLast
        }

        val propFile = rootProject.file("local.dev.properties")
        var content = "# Generated by switchTarget task\ntargetPlatform=$toPlatform\n"

        when (toPlatform) {
            "minecraft" -> {
                val toMcVer = project.findProperty("toMcVer")?.toString()
                val toMcLoader = project.findProperty("toMcLoader")?.toString()

                if (toMcVer == null || toMcLoader == null) {
                    logger.error("ERROR: For Minecraft, 'toMcVer' and 'toMcLoader' are required. Usage: ./gradlew switchTarget -PtoPlatform=minecraft -PtoMcVer=v1.20.1 -PtoMcLoader=fabric")
                    return@doLast
                }
                content += "targetMinecraftVersion=$toMcVer\n"
                content += "targetMinecraftLoader=$toMcLoader\n"
                logger.lifecycle("SUCCESS: Development target set to $toPlatform (Version: $toMcVer, Loader: $toMcLoader)")
            }
            // 可以為其他平台添加邏輯
            else -> {
                logger.lifecycle("SUCCESS: Development target set to $toPlatform")
            }
        }

        propFile.writeText(content.trim())

        logger.lifecycle("NOTE: Please re-import or reload Gradle project in your IDE to apply changes.")
    }
}
