import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.dsl.KotlinMultiplatformExtension
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    alias(libs.plugins.kotlin.multiplatform) apply false
    alias(libs.plugins.koin.compiler) apply false
}

allprojects {
    group = "com.doublemoon1119.mahjongcraft"
    version = "0.4.13-SNAPSHOT"

    // 必須先套用 base 插件，才能存取 base.archivesName
    apply(plugin = "base")

    // 取得 libs.versions.toml 中的預設 JVM Toolchain/Release 版本
    val jvmToolchainVersion = rootProject.libs.versions.jvm.toolchain.get().toInt()
    val jvmReleaseVersion = rootProject.libs.versions.jvm.release.get().toInt()

    // 統一設定 Kotlin jvmToolchain (這會自動影響 JavaCompile 和 KotlinCompile)
    plugins.withId("org.jetbrains.kotlin.multiplatform") {
        extensions.configure<KotlinMultiplatformExtension> {
            jvmToolchain(jvmToolchainVersion)
        }
    }

    afterEvaluate {
        // Java 編譯選項
        tasks.withType<JavaCompile>().configureEach {
            options.encoding = "UTF-8"
            options.release.set(jvmReleaseVersion)
        }

        // Kotlin 編譯選項
        tasks.withType<KotlinCompile>().configureEach {
            compilerOptions {
                jvmTarget.set(JvmTarget.fromTarget(jvmReleaseVersion.toString()))
                freeCompilerArgs.add("-Xjvm-default=all")
            }
        }
    }

    val baseExtension = extensions.getByType<BasePluginExtension>()
    tasks.withType<Jar>().configureEach {
        from(rootProject.file("LICENSE")) {
            rename { "${it}_${baseExtension.archivesName.get()}" }
        }
    }

    // 統一處理資源替換
    tasks.withType<ProcessResources>().configureEach {
        val props = mapOf("version" to project.version)
        inputs.properties(props)
        filesMatching(listOf("fabric.mod.json", "META-INF/neoforge.mods.toml")) {
            expand(props)
        }
    }
}

/**
 * 開發環境切換任務
 * 用法:
 *   - 切換到 Minecraft: ./gradlew switchTarget -PtoPlatform=minecraft -PtoMcVer=v1.20.1 -PtoMcLoader=fabric
 */
tasks.register("switchTarget") {
    group = "mahjong"
    description = "Updates local.dev.properties to switch the active development platform and version."

    doLast {
        val toPlatform = project.findProperty("toPlatform")?.toString()

        if (toPlatform == null) {
            logger.error("ERROR: Missing parameter 'toPlatform'. Usage: ./gradlew switchTarget -PtoPlatform=minecraft")
            return@doLast
        }

        val propFile = rootProject.file("local.dev.properties")
        var content = "# Generated by switchTarget task\ntargetPlatform=$toPlatform\n"

        when (toPlatform) {
            "minecraft" -> {
                val toMcVer = project.findProperty("toMcVer")?.toString()
                val toMcLoader = project.findProperty("toMcLoader")?.toString()

                if (toMcVer == null || toMcLoader == null) {
                    logger.error("ERROR: For Minecraft, 'toMcVer' and 'toMcLoader' are required. Usage: ./gradlew switchTarget -PtoPlatform=minecraft -PtoMcVer=v1.20.1 -PtoMcLoader=fabric")
                    return@doLast
                }
                content += "targetMinecraftVersion=$toMcVer\n"
                content += "targetMinecraftLoader=$toMcLoader\n"
                logger.lifecycle("SUCCESS: Development target set to $toPlatform (Version: $toMcVer, Loader: $toMcLoader)")
            }
            // 可以為其他平台添加邏輯
            else -> {
                logger.lifecycle("SUCCESS: Development target set to $toPlatform")
            }
        }

        propFile.writeText(content.trim())

        logger.lifecycle("NOTE: Please re-import or reload Gradle project in your IDE to apply changes.")
    }
}
