import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinJvmCompile

plugins {
    alias(libs.plugins.kotlin.jvm) apply false
}

allprojects {
    group = "doublemoon.mahjongcraft"
    version = "0.4.13-SNAPSHOT"

    // 必須先套用 base 插件，才能存取 base.archivesName
    apply(plugin = "base")

    val javaRelease = rootProject.libs.versions.java.release.get().toInt()

    tasks.withType<JavaCompile>().configureEach {
        options.encoding = "UTF-8"
        options.release.set(javaRelease)
    }

    tasks.withType<KotlinJvmCompile>().configureEach {
        compilerOptions {
            jvmTarget.set(JvmTarget.fromTarget(javaRelease.toString()))
            freeCompilerArgs.add("-Xjvm-default=all")
        }
    }

    val baseExtension = extensions.getByType<BasePluginExtension>()
    tasks.withType<Jar>().configureEach {
        from(rootProject.file("LICENSE")) {
            rename { "${it}_${baseExtension.archivesName.get()}" }
        }
    }

    // 統一處理資源替換
    tasks.withType<ProcessResources>().configureEach {
        val props = mapOf("version" to project.version)
        inputs.properties(props)
        filesMatching(listOf("fabric.mod.json", "META-INF/neoforge.mods.toml")) {
            expand(props)
        }
    }
}

/**
 * 環境切換任務
 * 用法範例: `./gradlew switchTarget -PtoVer=v1.20.1 -PtoLoader=fabric`
 */
tasks.register("switchTarget") {
    group = "mahjong"
    description = "Updates local.dev.properties to switch the active :target module."

    doLast {
        val toVer = project.findProperty("toVer")?.toString()
        val toLoader = project.findProperty("toLoader")?.toString() ?: "fabric"

        if (toVer == null) {
            logger.error("ERROR: Missing parameter 'toVer'. Usage: ./gradlew switchTarget -PtoVer=v1.21.1")
            return@doLast
        }

        val propFile = rootProject.file("local.dev.properties")
        val content = """
            # Generated by switchTarget task
            targetVersion=$toVer
            targetLoader=$toLoader
        """.trimIndent()

        propFile.writeText(content)

        logger.lifecycle("SUCCESS: Development target set to $toVer ($toLoader)")
        logger.lifecycle("NOTE: Please re-import or reload Gradle project in your IDE to apply changes.")
    }
}